# Generated by Django 5.1.7 on 2025-03-29 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator_username', models.CharField(max_length=100, verbose_name='操作人')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('record_id', models.CharField(max_length=100, verbose_name='记录ID')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除')], max_length=20, verbose_name='操作类型')),
                ('detail', models.JSONField(verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
