# Generated by Django 4.2.20 on 2025-03-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grant',
        ),
    ]
