# Generated by Django 4.2.20 on 2025-03-24 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0002_delete_grant'),
        ('user', '0002_remove_user_status_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(to='perm.permission', verbose_name='权限列表'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='perm.role', verbose_name='角色列表'),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='类型编码')),
                ('name', models.CharField(max_length=64, verbose_name='类型名称')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup', verbose_name='父级类型')),
                ('permissions', models.ManyToManyField(to='perm.permission', verbose_name='权限列表')),
                ('roles', models.ManyToManyField(to='perm.role', verbose_name='角色列表')),
                ('users', models.ManyToManyField(to='user.user', verbose_name='用户列表')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
            },
        ),
    ]
