# Generated by Django 4.2.20 on 2025-03-24 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_avatar_url_user_permissions_user_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='类型编码'),
        ),
    ]
