LOG_LEVEL: "DEBUG"

SETTINGS: {
  DEBUG: true,
  ALLOWED_HOSTS: [
    'dev.ycley.com',
    'localhost',
    '172.17.0.1:8000',
    '172.17.0.1',
    '127.0.0.1:8000',
    '127.0.0.1'
  ],
  CSRF_TRUSTED_ORIGINS: [
    'https://dev.ycley.com',
    'http://localhost:8000',
    'http://localhost',
    'http://127.0.0.1:8000',
    'http://127.0.0.1',
    'http://172.17.0.1:8000',
    'http://172.17.0.1'
  ],
  CORS_ALLOWED_ORIGINS: [
    'https://dev.ycley.com',
    'http://127.0.0.1:8080',
    'http://localhost:8080',
    'http://172.17.0.1:8080',
  ]
}

AES_KEY: "dTDR80ClnxN93QmX"


# Token配置
AUTH: {
  "COOKIE_ACCESS_TOKEN_NAME": "dev_idv_accessToken",  # accessToken name
  "COOKIE_REFRESH_TOKEN_NAME": "dev_idv_refreshToken",  # refreshToken name
  "COOKIE_USERNAME_NAME": "dev_idv_username_prod",
  
  "ACCESS_TOKEN_EXPIRE": 7200,  # 2小时
  "REFRESH_TOKEN_EXPIRE": 604800,  # 7天
  
  "JWT_SECRET": "JbzhCpYqofMDBb9A8AWte7jXiwp1FxI0TGWoq8FSI6DMrdPqtt",
  "JWT_ALGORITHM": "HS256",

  # "COOKIE_DOMAIN": ".ycley.com",  # 允许所有 ycley.com 的子域名访问
  "COOKIE_HTTPONLY": false,
  "COOKIE_SECURE": true,  # HTTPS 环境下设为 true
  # https://www.ruanyifeng.com/blog/2019/09/cookie-samesite.html
  "COOKIE_SAMESITE": "None",  # 跨域请求保持 None

}

MIDDLEWARE_WHITE_LIST: {
    "/api/v1/demo/health/": ["GET"],
    "/api/v1/auth/login/": ["POST"],
    "/api/v1/auth/logout/": ["POST"],
    "/api/v1/auth/refresh-token/": ["POST"],
}

MYSQL: {
  "HOST": "db_mysql",
  "PORT": 3306,
  "USER": "root",
  "PASSWORD": "Admin@123",
  "DB": "ops_arch_dashboard"
}

REDIS: {
  "HOST": "redis",
  "PORT": 6379,
  "PASSWORD": "Admin@123",
  "DB": {
    "DEFAULT": 0,
    # celery
    "CELERY": 1,
    # celery broker
    "CELERY_BROKER": 2,
    # 认证
    "AUTH": 3,
  },
}
