# Generated by Django 5.2.7 on 2025-10-03 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
            ],
            options={
                'verbose_name': '应用设置',
                'verbose_name_plural': '应用设置',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='链路名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='链路描述')),
                ('link_type', models.CharField(choices=[('domain', '域名链路'), ('network', '网络链路'), ('traffic', '流量链路'), ('application', '应用链路'), ('custom', '自定义链路')], max_length=50, verbose_name='链路类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='创建者')),
            ],
            options={
                'verbose_name': '链路',
                'verbose_name_plural': '链路',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('basic_info_list', models.JSONField(default=list, verbose_name='基础信息列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('position_x', models.FloatField(blank=True, null=True, verbose_name='X坐标')),
                ('position_y', models.FloatField(blank=True, null=True, verbose_name='Y坐标')),
                ('is_healthy', models.BooleanField(default=True, verbose_name='健康状态')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='monitor.link', verbose_name='所属架构图')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='NodeHealth',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_healthy', models.BooleanField(verbose_name='是否健康')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('probe_result', models.JSONField(default=dict, verbose_name='探活结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='monitor.node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '节点健康状态',
                'verbose_name_plural': '节点健康状态',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('direction', models.CharField(choices=[('up', '上'), ('down', '下'), ('left', '左'), ('right', '右')], max_length=10, verbose_name='连接方向')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='monitor.node', verbose_name='起始节点')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.link', verbose_name='所属架构图')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='monitor.node', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '节点连接',
                'verbose_name_plural': '节点连接',
                'unique_together': {('from_node', 'to_node', 'link')},
            },
        ),
    ]
