# Generated by Django 5.2.7 on 2025-10-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeconnection',
            name='direction',
        ),
    ]
