# Generated by Django 5.2.7 on 2025-10-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_nodeconnection_direction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodeconnection',
            unique_together={('from_node', 'to_node', 'link', 'is_del')},
        ),
    ]
