# Generated by Django 5.2.7 on 2025-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_node_is_healthy_node_healthy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodehealth',
            name='is_healthy',
        ),
        migrations.AddField(
            model_name='nodehealth',
            name='healthy_status',
            field=models.CharField(choices=[('unknown', '未知'), ('green', '健康'), ('yellow', '部分异常'), ('red', '异常')], default='unknown', max_length=20, verbose_name='健康状态'),
        ),
    ]
