# Generated by Django 5.2.7 on 2025-10-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_nodehealth_is_healthy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_type',
        ),
    ]
