# Generated by Django 5.2.7 on 2025-10-06 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_remove_link_link_type'),
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node_id', models.CharField(help_text='关联的节点ID', max_length=100)),
                ('alert_type', models.CharField(choices=[('HEALTH_CHECK_FAILED', 'Health Check Failed'), ('RESPONSE_TIME_SLOW', 'Response Time Slow'), ('SERVICE_UNAVAILABLE', 'Service Unavailable'), ('CONNECTION_TIMEOUT', 'Connection Timeout'), ('PARTIAL_HEALTH_CHECK_FAILED', 'Partial Health Check Failed')], help_text='告警类型', max_length=50)),
                ('alert_subtype', models.CharField(blank=True, default='', help_text='告警子类型，用于更细化的分类', max_length=100)),
                ('title', models.CharField(help_text='告警标题', max_length=200)),
                ('description', models.TextField(help_text='告警详细描述')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ACKNOWLEDGED', 'Acknowledged')], default='OPEN', help_text='告警状态', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='告警严重程度', max_length=20)),
                ('first_occurred', models.DateTimeField(auto_now_add=True, help_text='首次发生时间')),
                ('last_occurred', models.DateTimeField(auto_now=True, help_text='最后发生时间')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='解决时间', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='确认时间', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='确认人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='user.user')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to='user.user')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'db_table': 'alert',
                'ordering': ['-first_occurred'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('node_id', 'alert_type', 'alert_subtype', 'status'), name='unique_open_alert'), models.UniqueConstraint(condition=models.Q(('status', 'ACKNOWLEDGED')), fields=('node_id', 'alert_type', 'alert_subtype', 'status'), name='unique_acknowledged_alert')],
            },
        ),
    ]
