# Generated by Django 5.2.7 on 2025-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='healthy_status',
            field=models.CharField(choices=[('unknown', '未知'), ('green', '健康'), ('yellow', '部分异常'), ('red', '严重异常')], default='unknown', max_length=20, verbose_name='健康状态'),
        ),
        migrations.AlterField(
            model_name='nodehealth',
            name='healthy_status',
            field=models.CharField(choices=[('unknown', '未知'), ('green', '健康'), ('yellow', '部分异常'), ('red', '严重异常')], default='unknown', max_length=20, verbose_name='健康状态'),
        ),
    ]
