# Generated by Django 5.2.7 on 2025-10-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_node_healthy_status_and_more'),
        ('user', '0001_initial'),  # Assuming user app migration exists
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='silenced_at',
            field=models.DateTimeField(blank=True, help_text='静默时间', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='silenced_by',
            field=models.ForeignKey(blank=True, help_text='静默人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silenced_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='silenced_reason',
            field=models.TextField(blank=True, help_text='静默原因', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='silenced_until',
            field=models.DateTimeField(blank=True, help_text='静默结束时间', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ACKNOWLEDGED', 'Acknowledged'), ('SILENCED', 'Silenced')], default='OPEN', help_text='告警状态', max_length=20),
        ),
    ]