# Generated by Django 5.2.7 on 2025-10-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_add_silence_fields_to_alert'),
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='silenced_by',
            field=models.ForeignKey(blank=True, help_text='静默人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silenced_alerts', to='user.user'),
        ),
    ]
