# Generated by Django 5.2.7 on 2025-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_alter_alert_silenced_by'),
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='unique_acknowledged_alert',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='acknowledged_by',
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SILENCED', 'Silenced')], default='OPEN', help_text='告警状态', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SILENCED')), fields=('node_id', 'alert_type', 'alert_subtype', 'status'), name='unique_silenced_alert'),
        ),
    ]
