# Generated by Django 5.2.7 on 2025-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_remove_alert_unique_acknowledged_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(help_text='告警类型', max_length=50),
        ),
    ]
