# Generated by Django 5.2.7 on 2025-10-08 03:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_alter_alert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthStats',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(help_text='统计项唯一键', max_length=100, unique=True)),
                ('value', models.TextField(help_text='统计值')),
                ('meta_info', models.JSONField(blank=True, help_text='附加信息', null=True)),
            ],
            options={
                'verbose_name': '系统健康统计',
                'verbose_name_plural': '系统健康统计',
                'db_table': 'system_health_stats',
            },
        ),
    ]
