# Generated by Django 5.2.7 on 2025-10-09 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_systemhealthstats'),
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushPlusConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config_type', models.CharField(choices=[('GLOBAL', '全局配置'), ('DEFAULT', '默认配置')], default='GLOBAL', help_text='配置类型', max_length=20)),
                ('name', models.CharField(help_text='配置名称', max_length=100, unique=True)),
                ('token', models.CharField(help_text='PushPlus Token', max_length=100)),
                ('title_prefix', models.CharField(blank=True, default='', help_text='标题前缀', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('msg_type', models.CharField(choices=[('txt', '文本消息'), ('html', 'HTML消息'), ('markdown', 'Markdown消息'), ('json', 'JSON消息')], default='txt', help_text='消息类型', max_length=20)),
                ('template_type', models.CharField(choices=[('alert', '告警消息模板'), ('notification', '通知消息模板'), ('custom', '自定义消息模板')], default='alert', help_text='模板类型', max_length=20)),
                ('content_template', models.TextField(help_text='内容模板，支持变量替换')),
                ('apply_to_all_alerts', models.BooleanField(default=True, help_text='是否应用于所有告警')),
                ('alert_severity_filter', models.JSONField(default=list, help_text="告警严重程度过滤器，例如['CRITICAL', 'HIGH']")),
                ('topic_list', models.JSONField(default=list, help_text='订阅组列表，以英文逗号分隔')),
                ('webhook_list', models.JSONField(default=list, help_text='Webhook列表')),
                ('extra_params', models.JSONField(default=dict, help_text='额外参数，以JSON格式存储')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pushplus_configs', to='user.user')),
                ('updated_by', models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pushplus_configs', to='user.user')),
            ],
            options={
                'verbose_name': 'PushPlus配置',
                'verbose_name_plural': 'PushPlus配置',
                'db_table': 'pushplus_config',
                'ordering': ['-create_time'],
            },
        ),
    ]
