# Generated by Django 5.2.7 on 2025-10-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_pushplusconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='check_single_point',
            field=models.BooleanField(default=False, verbose_name='是否检测单点'),
        ),
    ]
