# Generated by Django 5.2.7 on 2025-10-25 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_link_check_single_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('is_ping_disabled', models.BooleanField(default=False, verbose_name='是否禁ping')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_info_items', to='monitor.node', verbose_name='关联节点')),
            ],
            options={
                'verbose_name': '基础信息',
                'verbose_name_plural': '基础信息',
                'ordering': ['-create_time'],
                'constraints': [models.UniqueConstraint(fields=('node', 'host', 'port'), name='unique_node_host_port')],
            },
        ),
    ]
