# Generated by Django 5.2.7 on 2025-10-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_baseinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='basic_info_list',
        ),
    ]
