# Generated by Django 5.2.7 on 2025-10-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_remove_node_basic_info_list'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baseinfo',
            name='unique_node_host_port',
        ),
        migrations.AddConstraint(
            model_name='baseinfo',
            constraint=models.UniqueConstraint(fields=('host', 'port'), name='unique_node_host_port'),
        ),
    ]
