# Generated by Django 5.2.7 on 2025-10-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_remove_baseinfo_unique_node_host_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='is_healthy',
            field=models.BooleanField(blank=True, null=True, verbose_name='健康状态'),
        ),
    ]
