# Generated by Django 5.2.7 on 2025-10-26 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_baseinfo_is_healthy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeBaseInfo',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_ping_disabled', models.BooleanField(default=False, verbose_name='是否禁ping（节点特定）')),
            ],
            options={
                'verbose_name': '节点服务关联',
                'verbose_name_plural': '节点服务关联',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'ordering': ['-create_time'], 'verbose_name': '基础服务信息', 'verbose_name_plural': '基础服务信息'},
        ),
        migrations.RemoveConstraint(
            model_name='baseinfo',
            name='unique_node_host_port',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='node',
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddConstraint(
            model_name='baseinfo',
            constraint=models.UniqueConstraint(fields=('host', 'port'), name='unique_host_port_global'),
        ),
        migrations.AddField(
            model_name='nodebaseinfo',
            name='base_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_associations', to='monitor.baseinfo', verbose_name='服务信息'),
        ),
        migrations.AddField(
            model_name='nodebaseinfo',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_base_info_items', to='monitor.node', verbose_name='关联节点'),
        ),
        migrations.AlterUniqueTogether(
            name='nodebaseinfo',
            unique_together={('node', 'base_info')},
        ),
    ]
