# Generated by Django 5.2.7 on 2025-10-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_nodebaseinfo_alter_baseinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodebaseinfo',
            name='is_ping_disabled',
        ),
    ]
