# Generated by Django 5.2.7 on 2025-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_remove_nodebaseinfo_is_ping_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
